import {
  AlertTriangle,
  AudioLines,
  BadgeCheck,
  BarChart3,
  BookMarked,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  ChartNoAxesColumn,
  Check,
  CheckCircle2,
  Circle,
  Clapperboard,
  ClipboardCheck,
  Compass,
  Cpu,
  Crown,
  Dumbbell,
  FileCode2,
  FileText,
  Flame,
  FlaskConical,
  FolderKanban,
  Gauge,
  Gem,
  Goal,
  GraduationCap,
  Hammer,
  Heart,
  Layers3,
  Library,
  Lightbulb,
  LineChart,
  Lock,
  Map,
  Medal,
  MessageCircleQuestion,
  MessageSquare,
  Microscope,
  MoonStar,
  Music,
  Minus,
  NotebookPen,
  Orbit,
  Palette,
  PenTool,
  Plus,
  Repeat,
  Rocket,
  ScrollText,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  Sunrise,
  Swords,
  Target,
  Timer,
  Trophy,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

const ICONS = {
  activity: Gauge,
  alert: AlertTriangle,
  artifact: FolderKanban,
  audio: AudioLines,
  badge: BadgeCheck,
  bar_chart: BarChart3,
  bolt: Zap,
  book: BookOpen,
  book_marked: BookMarked,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  challenge: Swords,
  chart: ChartNoAxesColumn,
  check: Check,
  check_circle: CheckCircle2,
  circle: Circle,
  clipboard_check: ClipboardCheck,
  clapperboard: Clapperboard,
  code: FileCode2,
  compass: Compass,
  cpu: Cpu,
  crown: Crown,
  defense: ShieldCheck,
  design: Palette,
  draft: NotebookPen,
  dumbbell: Dumbbell,
  file: FileText,
  flame: Flame,
  flask: FlaskConical,
  folder_kanban: FolderKanban,
  gauge: Gauge,
  gem: Gem,
  goal: Goal,
  graduation: GraduationCap,
  grid: Layers3,
  hammer: Hammer,
  heart: Heart,
  layers: Layers3,
  library: Library,
  lightbulb: Lightbulb,
  line_chart: LineChart,
  lock: Lock,
  map: Map,
  medal: Medal,
  message: MessageSquare,
  message_question: MessageCircleQuestion,
  microscope: Microscope,
  minus: Minus,
  moon: MoonStar,
  music: Music,
  orbit: Orbit,
  pen: PenTool,
  plus: Plus,
  repeat: Repeat,
  rocket: Rocket,
  scroll: ScrollText,
  share: Share2,
  shield: Shield,
  shield_check: ShieldCheck,
  sparkles: Sparkles,
  sprout: Sprout,
  sunrise: Sunrise,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  wrench: Wrench,
  x: X,
}

export default function IconGlyph({
  name = 'sparkles',
  size = 18,
  strokeWidth = 2.2,
  color = 'currentColor',
  style,
  ...props
}) {
  const Icon = ICONS[name] || Sparkles
  return <Icon size={size} strokeWidth={strokeWidth} color={color} style={style} {...props} />
}
