import { FULL_AI_ROUTED_RESPONSE_SCHEMA } from '@/lib/templateSvgRenderers/schemas'

export const FULL_AI_SVG_RESPONSE_FORMAT = {
  type: 'json_schema',
  json_schema: {
    name: 'pathai_full_ai_svg_v1',
    strict: true,
    schema: FULL_AI_ROUTED_RESPONSE_SCHEMA,
  },
}

export function buildFullAiSvgPrompt({ concept = '', validationFeedback = '' } = {}) {
  return [
    'Generate one fresh, accurate educational diagram for this exact request, not decorative art.',
    'Return schema-valid JSON only. Choose exactly one `kind` from the response schema.',
    'The response object includes every possible payload key for strict-mode compatibility. Set the payload property matching `kind` to real data and set every other payload property to null. If `kind` is `freeform`, set `svg` to the SVG string and all template payloads to null. If `kind` is a template, set `svg` to null.',
    'TEMPLATE SELECTION. Prefer a template whenever the concept fits one of these structures:',
    '- flowchart: algorithms, processes, for/while loops, login flows, decision trees.',
    '- cycle: water cycle, cell cycle, feedback loops, Krebs cycle, photosynthesis stages.',
    '- hierarchy: class inheritance, DOM, taxonomies, org charts, decision trees.',
    '- timeline: history, project phases, ordered events with dates.',
    '- comparison: side-by-side A/B, language A vs B, before/after.',
    '- layered_stack: OSI, tech stacks, geology layers, abstraction layers.',
    '- quadrant: 2x2 matrices, Eisenhower, BCG, risk/effort.',
    '- network: graphs, dependencies, social networks, state diagrams without a clear flow.',
    '- equation_breakdown: annotate parts of one equation.',
    '- annotated_callouts: label parts of a structure.',
    '- code_execution: line-by-line variable/output tracing.',
    '- algorithm_step: data-structure step-throughs such as sort/search on arrays.',
    '- venn: set theory and overlapping categories.',
    '- number_line: math intervals and inequalities.',
    '- table: truth tables and compact comparison matrices.',
    '- state_machine: finite state machines, regex automata, protocol states.',
    '- bar_chart: simple categorical comparisons.',
    'Prefer a template. Choose `kind: "freeform"` ONLY when no template fits the concept essential structure, such as chess positions, anatomy, molecules, circuits, custom spatial diagrams, or domain-specific illustrations. When a template fits, fill its data fully; never return a template kind with an empty or near-empty payload.',
    'For template kinds, return only the structured data requested by that kind. Do not include SVG. The server renderer handles layout and styling.',
    'For `kind: "freeform"` only, include `svg`, and the svg must start with <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 600".',
    'The SVG construction and layout rules below apply to `kind: "freeform"`. For template kinds, follow the schema and provide accurate content data; the server-side renderer will handle layout.',
    'Output must be well-formed XML. Every < > and & inside text content or attribute values MUST be escaped as &lt; &gt; and &amp;. Inequalities, math expressions, and code snippets that contain < or > (for example "x < 5", "i < 3", "a > b", "y > x") break the XML parser if written literally - either escape them as &lt; / &gt;, rewrite in words ("x less than 5"), or use unicode arrows (→, ←). Never put a literal < or > between text tags.',
    'Before writing the SVG, internally plan the exact subject, the must-have domain facts, the simplest useful visual type, the layout grid, and where labels will go. Do not output this plan.',
    'Accuracy is the top priority. Use standard domain conventions and draw the specific requested thing, not a nearby generic example. If exact precision is not possible, draw a conservative simplified version and label it as simplified rather than inventing false details.',
    'The diagram MUST be about exactly the requested concept. Put the requested concept words in the title or visible labels.',
    'Do not substitute a nearby example. If the concept says King\'s Indian Opening, do not draw Italian Game. If it says Arduino, do not draw a generic circuit.',
    'Treat every request as unique. Do not reuse canned examples or generic templates.',
    'Use the PathAI visual language: dark background #07111f, panel fill #0b1725, primary teal #14f1c9, cyan #38bdf8, yellow #facc15, orange #f97316, red #ef4444, text #f8fafc, muted text #94a3b8, borders #23404f.',
    'Use one clean outer frame and one main drawing area. Avoid nested panels, stacked label pills, decorative cards, or random boxes unless a box is a real process step or a necessary callout.',
    'Use rounded rectangles only for real nodes/steps/callouts: rx 12-20. Do not put tiny axis labels, single-letter labels, or chemical subscripts inside boxed pills. Keep strokes smooth with rounded linecaps and joins.',
    'Use bold, legible text: labels and node text at font-size 15-19 with font-weight 600-700, the title at font-size 26-30 with font-weight 800, captions at font-size 13-14. Size every callout box to fully contain its text with even padding so no character touches or crosses the box edge. Keep output under 42kb.',
    'Reserve y=24-82 for the title. Put the main drawing in x=85..815 and y=115..470. Reserve y=500..560 for one optional short caption only. Center the composition around x=450 and y=300, fill the space evenly, align elements to a tidy invisible grid, and do not leave one side empty. Leave at least 28px between labels and major shapes.',
    'Choose one clean layout template before drawing: process = evenly spaced vertical or horizontal steps; circuit = schematic-first with one loop and clear symbols; chess = one centered 8x8 board with a short side note; math/physics = one graph/free-body/geometry panel with labels outside the drawing; biology/chemistry = one central structure with leader-line labels. Do not mix templates unless the user explicitly asks for multiple views.',
    'Before placing any text, allocate label-safe zones first: title lane y=34..76, left margin lane x=90..205, right margin lane x=695..810, bottom caption lane y=505..552, and any internal callout lane you need. Treat every label as a rectangle with 12px padding around it. No wire, arrow, path, plotted curve, object edge, icon detail, or component outline may pass through that padded label rectangle.',
    'Use this construction order: background and frame first, major objects second, reserve empty label zones third, route all wires/arrows/paths around those zones fourth, then draw label backing pads and text last. Do not solve overlap by simply drawing text on top of a line; move the label, bend the line, or add a short leader line from a clean label position.',
    'When a label belongs to an object, place it in a clear empty band above, below, or beside the object. If the object is too small or busy, put the label outside the object with a thin leader line. Never place a label directly over a wire, arrow, current path, plotted curve, board trace, chess piece, molecule bond, or detailed drawing.',
    'For graph diagrams: use a single plot panel. Plot area should be roughly x=210..700 and y=150..430. Put the y-axis at x=210 and the x-axis at y=430. Put axis labels outside the axes: y label left of the vertical axis, x label below/right of the horizontal axis. Put callouts outside the plot area in the left/right margin lanes. No label box may cover the plotted line, point markers, arrowheads, or axes.',
    'For gradient descent or loss landscapes, follow this exact composition unless the user asks for something else: outer panel rect x=70 y=70 width=760 height=480 rx=24; title centered at x=450 y=116; plot axes from (210,430) to (700,430) and (210,430) to (210,165); draw ONE cyan U-shaped loss curve `M250 210 C330 420 570 420 660 210`; draw a yellow current point on the left branch near (285,270); draw 3 teal update arrows along the left branch toward the bottom minimum using points near (335,335), (395,385), (455,405); draw the minimum as a teal point at (455,405).',
    'For gradient descent labels: place "Current model" in a small callout box at x=95 y=235 width=120 height=42; place "Update step" at x=570 y=230 width=125 height=42; place "Minimum loss" at x=590 y=380 width=135 height=42. Draw thin muted leader lines from those boxes to their targets. Do not put any of those boxes inside the curve path, on top of arrows, or on top of point markers. The bottom caption must be one line at y=520.',
    'For gradient descent accuracy: the loss curve MUST be a valley, not a hill. In SVG coordinates the minimum point should be lower on the screen, near y=405, and the sides of the curve should rise upward toward y≈210. Update arrows must move from high loss toward lower loss, ending near the bottom-center minimum. Never place "Minimum loss" at the top of the curve.',
    'For any plotted learning concept, keep the explanatory callouts to the sides: left side for "current/start", right or lower side for "minimum/result", and one short caption at the bottom. The central plot should be mostly lines, points, and arrows, not boxes.',
    'If the user asks for multiple views, split the canvas into clearly separated sections with gutters of at least 34px and short section headings. Never squeeze several diagrams into one shared crowded panel.',
    'Keep every element fully inside the canvas with a 30px safety margin: no rect, circle, line, path, arrowhead, text, or caption may extend beyond x=30..870 or y=30..570. Estimate text width as about 0.6 x font-size per character. A label whose right edge would pass x=815 must use text-anchor="end"; a label whose left edge would pass x=85 must use text-anchor="start"; otherwise center it with text-anchor="middle".',
    'Ideal layout rules: avoid overlapping boxes, overlapping text, off-canvas text, cramped labels, and crossing arrows. These are quality goals, not a reason to omit important accurate content.',
    'Minimize labels. Use only the labels needed to teach the point; when the concept needs many details, move secondary explanation into one short caption instead of crowding the drawing. Prefer 4-8 well-placed labels, but use more if the concept truly needs them.',
    'If a label would be long, wrap it into 2 short lines with <tspan> or move the detail into one short caption near the bottom. Do not use long single-line text inside the drawing.',
    'Any bottom caption must stay within x=85..815 and y=505..555 at font-size 13-14 and wrap across up to 2 lines with <tspan> so no line exceeds ~78 characters. Never let the caption run past the canvas edges or overlap the drawing.',
    'Never let text overlap drawings, arrows, nodes, pieces, wires, curves, or other text. Use direct labels as plain text whenever possible. Use a rounded callout box only when it improves readability, with dark fill and 8-12px padding, then connect it with a thin leader line.',
    'Prefer one visual focus over many annotations. If you need a callout, make it small, outside the core drawing, and connected by a leader line. Do not use more than 3 boxed callouts unless the user explicitly asks for a labeled parts diagram.',
    'Route every connector from the edge of one shape to the edge of the next without passing through any node, label, or other arrow; route loop-back or return arrows around the outside of the shapes. Keep arrowheads small and proportional, about 8-12px long, never oversized or chunky.',
    'For chemical formulas or any text with subscripts or superscripts (CO2, H2O, C6H12O6), keep the entire formula including its small digits inside the box with extra right padding, and size the box for the full width.',
    'Prefer direct labels near objects, but if space is tight, move labels outside the drawing and use leader lines. Do not place white text on bright shapes.',
    'For dense visuals, first spread elements out, wrap or shorten labels, and use leader lines to avoid crowding; reduce the number of labels only if it is still crowded, and keep every element the concept genuinely requires. A clean correct diagram beats a busy one. Do not combine many separate diagram types unless the user explicitly asks for multiple views.',
    'If any label, caption, node, arrow, or drawing would violate the spacing or canvas rules, change the layout before returning: resize the drawing, move the label outside with a leader line, wrap the text, or simplify secondary details. Never knowingly return a clipped, overlapping, or cramped SVG.',
    'For timelines or any left-to-right sequence: draw one horizontal axis with events ordered earliest on the left to latest on the right, and point the axis arrowhead rightward toward the latest event. Give each event both its name and its date, and stagger the labels alternately above and below the axis, each at least 28px clear of the axis, with at least 24px horizontal gap between neighboring labels and their callout boxes. If labels would still collide, shorten or wrap the labels and spread the events across the full width; only drop a label as a last resort, and never drop a core event of the requested concept.',
    'Use real domain conventions: electronics need pins, wires, schematic symbols, resistor values, LED polarity, and ground; chess needs an 8x8 board, coordinates, legal piece placement, and clear pieces; math and physics need axes, vectors, free-body diagrams, equations, units, and precise labels.',
    'For biology, show recognizable structures with labels. For chemistry, show atoms/bonds/reaction arrows. For systems, show actors, direction of data flow, and labels.',
    'For circuits, show actual connection paths with polarity and current direction. Use a schematic-first layout unless the user asks for a physical breadboard. Keep a separate wiring lane and label lane: Arduino/board labels go in a clear top strip or outside the board; pin labels sit outside board edges; breadboard labels sit above or below the breadboard, never across a wire lane; resistor/LED labels sit above or below their symbols or in nearby callouts. Route wires only between pins/terminals and bend them around all label boxes with at least 18px clearance.',
    'For physical electronics diagrams, avoid putting text inside large colored parts if wires will cross that area. If a board, breadboard, resistor, LED, battery, or sensor label would collide with the drawing, move the label just outside the part and connect it with a leader line. Never run a wire through the words "Arduino", "Breadboard", "Resistor", "LED", "GND", pin labels, or callout labels.',
    'For named chess openings or mates, show the real position after the named move sequence with coordinates. For formulas, show the geometric or physical relationship, not a generic icon.',
    'If the concept is "number line", draw an actual number line with arrows, evenly spaced ticks, integer labels, zero marked, and any requested inequality highlighted.',
    'If the concept is arbitrary, choose the most concrete accurate visual for it. Only use a concept map when the input is genuinely abstract and no better visual exists.',
    'Never return a generic concept map for concrete visual requests like number line, chessboard, circuit, graph, anatomy, timeline, equation, force diagram, or process cycle.',
    'If unsure, make a conservative labeled diagram that visibly names the requested concept instead of inventing unrelated facts or fake geometry.',
    'Do not use scripts, event handlers, external href/src, data URLs, style attributes, or foreignObject.',
    'Make every diagram look intentionally designed and human-made: consistent box sizes and corner radii, elements aligned to a tidy grid, even spacing, and balanced visual weight, not scattered or auto-generated. Prefer clean textbook clarity over decorative complexity.',
    'Before finalizing, mentally inspect the SVG: exact concept match, no unrelated example, all important shapes visible, every coordinate inside the 900x600 viewBox, text inside canvas, callouts sized correctly, no obvious overlaps, no cramped bottom caption, and no unnecessary boxed labels. Repair the layout before returning.',
    validationFeedback ? 'This is a repair pass. If the current layout is crowded, rebuild the layout cleanly from scratch; otherwise move, resize, shorten, or wrap only the offending elements. Keep the same concept and every detail a correct diagram needs - do not delete important content just to satisfy visual polish checks.' : '',
    validationFeedback ? `Problems to fix: ${validationFeedback}` : '',
    `Concept: ${concept}`,
  ].filter(Boolean).join('\n')
}
